//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHttpServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleHttpServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Continue
        ///101 Switching Protocols
        ///102 Processing
        ///200 OK
        ///201 Created
        ///202 Accepted
        ///203 Non-Authoritative Information
        ///204 No Content
        ///205 Reset Content
        ///206 Partial Content
        ///207 Multi-Status
        ///208 Already Reported
        ///226 IM Used
        ///300 Multiple Choices
        ///301 Moved Permanently
        ///302 Found
        ///303 See Other
        ///304 Not Modified
        ///305 Use Proxy
        ///307 Temporary Redirect
        ///308 Permanent Redirect
        ///400 Bad Request
        ///401 Unauthorized
        ///402 Payment Required
        ///403 Forbidden
        ///404 Not Found
        ///405 Method Not Allowed
        ///406 Not Accepta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HttpResponseStatusMessages {
            get {
                return ResourceManager.GetString("HttpResponseStatusMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;
        ///        400 Bad Request
        ///    &lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;h1&gt;
        ///        400 Bad Request
        ///    &lt;/h1&gt;
        ///    &lt;p&gt;
        ///        The server cannot process the request due to a client error
        ///    &lt;/p&gt;
        ///    &lt;hr&gt;
        ///    &lt;p&gt;
        ///        Simple HTTP server
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ServerResponsePage400 {
            get {
                return ResourceManager.GetString("ServerResponsePage400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;
        ///        404 Not Found
        ///    &lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;h1&gt;
        ///        404 Not Found
        ///    &lt;/h1&gt;
        ///    &lt;p&gt;
        ///        The server cannot find the requested resource
        ///    &lt;/p&gt;
        ///    &lt;hr&gt;
        ///    &lt;p&gt;
        ///        Simple HTTP server
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ServerResponsePage404 {
            get {
                return ResourceManager.GetString("ServerResponsePage404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;
        ///        501 Not Implemented
        ///    &lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;h1&gt;
        ///        501 Not Implemented
        ///    &lt;/h1&gt;
        ///    &lt;p&gt;
        ///        The server does not support the functionality required to fulfill the request
        ///    &lt;/p&gt;
        ///    &lt;hr&gt;
        ///    &lt;p&gt;
        ///        Simple HTTP server
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ServerResponsePage501 {
            get {
                return ResourceManager.GetString("ServerResponsePage501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;
        ///        505 HTTP Version Not Supported
        ///    &lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;h1&gt;
        ///        505 HTTP Version Not Supported
        ///    &lt;/h1&gt;
        ///    &lt;p&gt;
        ///        The HTTP version used in the request is not supported by the server
        ///    &lt;/p&gt;
        ///    &lt;hr&gt;
        ///    &lt;p&gt;
        ///        Simple HTTP server
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ServerResponsePage505 {
            get {
                return ResourceManager.GetString("ServerResponsePage505", resourceCulture);
            }
        }
    }
}
