//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHttpServer.Resources.Entities.HttpResponse.Details {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpResponseDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpResponseDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleHttpServer.Resources.Entities.HttpResponse.Details.HttpResponseDetails", typeof(HttpResponseDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your client sent an invalid request.
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource using the credentials you provided.
        /// </summary>
        internal static string _401 {
            get {
                return ResourceManager.GetString("401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this resource.
        /// </summary>
        internal static string _403 {
            get {
                return ResourceManager.GetString("403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found on the server.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target resource does not support this method.
        /// </summary>
        internal static string _405 {
            get {
                return ResourceManager.GetString("405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not find an appropriate representation of the requested resource.
        /// </summary>
        internal static string _406 {
            get {
                return ResourceManager.GetString("406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this resource requires proxy authentication.
        /// </summary>
        internal static string _407 {
            get {
                return ResourceManager.GetString("407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is taking too long to process, the server has timed out.
        /// </summary>
        internal static string _408 {
            get {
                return ResourceManager.GetString("408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request conflicts with the current state of the target resource.
        /// </summary>
        internal static string _409 {
            get {
                return ResourceManager.GetString("409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is no longer available on the server.
        /// </summary>
        internal static string _410 {
            get {
                return ResourceManager.GetString("410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is missing the &quot;Content-Length&quot; header.
        /// </summary>
        internal static string _411 {
            get {
                return ResourceManager.GetString("411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified precondition has failed for this request.
        /// </summary>
        internal static string _412 {
            get {
                return ResourceManager.GetString("412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request entity exceeds the limits defined by the server.
        /// </summary>
        internal static string _413 {
            get {
                return ResourceManager.GetString("413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the request URL exceeds the limits defined by the server.
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request entity is in an unsupported format.
        /// </summary>
        internal static string _415 {
            get {
                return ResourceManager.GetString("415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot serve the requested ranges.
        /// </summary>
        internal static string _416 {
            get {
                return ResourceManager.GetString("416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expectation specified in the &quot;Expect&quot; request header could not be met.
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot provide a response to this request.
        /// </summary>
        internal static string _421 {
            get {
                return ResourceManager.GetString("421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protocol specified in the request needs to be upgraded.
        /// </summary>
        internal static string _426 {
            get {
                return ResourceManager.GetString("426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request to the specified resource must be conditional.
        /// </summary>
        internal static string _428 {
            get {
                return ResourceManager.GetString("428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent too many requests.
        /// </summary>
        internal static string _429 {
            get {
                return ResourceManager.GetString("429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the request headers field exceeds the limits defined by the server.
        /// </summary>
        internal static string _431 {
            get {
                return ResourceManager.GetString("431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is not available due to legal reasons.
        /// </summary>
        internal static string _451 {
            get {
                return ResourceManager.GetString("451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an error that prevented it from fulfilling the request.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not support the functionality required to fulfill the request.
        /// </summary>
        internal static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server received an invalid response while acting as a gateway or proxy.
        /// </summary>
        internal static string _502 {
            get {
                return ResourceManager.GetString("502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is temporarily unable to fulfill the request.
        /// </summary>
        internal static string _503 {
            get {
                return ResourceManager.GetString("503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not get a response in time from while acting as a gateway or proxy.
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protocol version specified in the request is not supported by the server.
        /// </summary>
        internal static string _505 {
            get {
                return ResourceManager.GetString("505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen variant resource is configured to engage in content negotiation.
        /// </summary>
        internal static string _506 {
            get {
                return ResourceManager.GetString("506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the described extensions specified in the request are not supported.
        /// </summary>
        internal static string _510 {
            get {
                return ResourceManager.GetString("510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network access requires authentication.
        /// </summary>
        internal static string _511 {
            get {
                return ResourceManager.GetString("511", resourceCulture);
            }
        }
    }
}
