//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHttpServer.Resources.Entities.HttpResponse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpResponseStatusMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpResponseStatusMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleHttpServer.Resources.Entities.HttpResponse.HttpResponseStatusMessages", typeof(HttpResponseStatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching Protocols.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Authoritative Information.
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Content.
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Content.
        /// </summary>
        internal static string _205 {
            get {
                return ResourceManager.GetString("205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Content.
        /// </summary>
        internal static string _206 {
            get {
                return ResourceManager.GetString("206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Choices.
        /// </summary>
        internal static string _300 {
            get {
                return ResourceManager.GetString("300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Permanently.
        /// </summary>
        internal static string _301 {
            get {
                return ResourceManager.GetString("301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string _302 {
            get {
                return ResourceManager.GetString("302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Other.
        /// </summary>
        internal static string _303 {
            get {
                return ResourceManager.GetString("303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Modified.
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Redirect.
        /// </summary>
        internal static string _307 {
            get {
                return ResourceManager.GetString("307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Redirect.
        /// </summary>
        internal static string _308 {
            get {
                return ResourceManager.GetString("308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string _401 {
            get {
                return ResourceManager.GetString("401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string _403 {
            get {
                return ResourceManager.GetString("403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Not Allowed.
        /// </summary>
        internal static string _405 {
            get {
                return ResourceManager.GetString("405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Acceptable.
        /// </summary>
        internal static string _406 {
            get {
                return ResourceManager.GetString("406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Authentication Required.
        /// </summary>
        internal static string _407 {
            get {
                return ResourceManager.GetString("407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Timeout.
        /// </summary>
        internal static string _408 {
            get {
                return ResourceManager.GetString("408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        internal static string _409 {
            get {
                return ResourceManager.GetString("409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone.
        /// </summary>
        internal static string _410 {
            get {
                return ResourceManager.GetString("410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Required.
        /// </summary>
        internal static string _411 {
            get {
                return ResourceManager.GetString("411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition Failed.
        /// </summary>
        internal static string _412 {
            get {
                return ResourceManager.GetString("412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Too Large.
        /// </summary>
        internal static string _413 {
            get {
                return ResourceManager.GetString("413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI Too Long.
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Media Type.
        /// </summary>
        internal static string _415 {
            get {
                return ResourceManager.GetString("415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Not Satisfiable.
        /// </summary>
        internal static string _416 {
            get {
                return ResourceManager.GetString("416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectation Failed.
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misdirected Request.
        /// </summary>
        internal static string _421 {
            get {
                return ResourceManager.GetString("421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Required.
        /// </summary>
        internal static string _426 {
            get {
                return ResourceManager.GetString("426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition Required.
        /// </summary>
        internal static string _428 {
            get {
                return ResourceManager.GetString("428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Requests.
        /// </summary>
        internal static string _429 {
            get {
                return ResourceManager.GetString("429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Header Fields Too Large.
        /// </summary>
        internal static string _431 {
            get {
                return ResourceManager.GetString("431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable For Legal Reasons.
        /// </summary>
        internal static string _451 {
            get {
                return ResourceManager.GetString("451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        internal static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gateway.
        /// </summary>
        internal static string _502 {
            get {
                return ResourceManager.GetString("502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        internal static string _503 {
            get {
                return ResourceManager.GetString("503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Timeout.
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Version Not Supported.
        /// </summary>
        internal static string _505 {
            get {
                return ResourceManager.GetString("505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Also Negotiates.
        /// </summary>
        internal static string _506 {
            get {
                return ResourceManager.GetString("506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Extended.
        /// </summary>
        internal static string _510 {
            get {
                return ResourceManager.GetString("510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Authentication Required.
        /// </summary>
        internal static string _511 {
            get {
                return ResourceManager.GetString("511", resourceCulture);
            }
        }
    }
}
